import type { Metadata } from 'next'
import '@/app/globals.scss'
import josefinSans from '@/app/fonts'
import Providers from '@/app/components/providers'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html className='dark' lang='en'>
			<body className={`${josefinSans.className} antialiased dark:bg-[#000000] dark:text-[#f6f6f6]`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
